version: '2'

services:
  postgres:
    image: 'postgres:15.1-alpine'
    container_name: 'infopet-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

  app:
    image: lesn0y/info-pet-backend:0.0.1
    ports:
      - '8080:8080'
    depends_on:
      - postgres
#  angular_app:
#    image: holiday223/angular-app:0.0.1
#    ports:
#      - '443:80'
#    depends_on:
#      - app

  python_script:
    image: holiday223/python_script:0.0.1
    container_name: 'infopet-script'
    depends_on:
      - postgres

  python_script2:
    image: holiday223/python_script2:0.0.1
    container_name: 'infopet-script2'
    depends_on:
      - postgres


volumes:
  db-data: